version: '3.9'

networks:
  edge: {}
  appnet: {}

volumes:
  caddy_data:
  caddy_config:
  mysql_data:

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - crm_server
    networks:
      - edge
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: >
      sh -c 'cat <<EOF> /etc/caddy/Caddyfile
      {
        email ngankang2@gmail.com

      }
      api.157-10-73-201.sslip.io {
        reverse_proxy crm_server:8000
      }
      EOF
      && caddy run --config /etc/caddy/Caddyfile --adapter caddyfile' 
  
  crm_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi_api:latest
    container_name: fastapi-api
    restart: unless-stopped
    working_dir: /app
    networks:
      - appnet
      - edge
    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    expose: 
      - "8000"

  mysql:
    image: mysql:8.0.42
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [appnet]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    
