version: '3.8'

services:
  crm_server:
    build:
      context:
      dockerfiles: Dockerfile
    container_name: crm-app
    restart: unless-stopped
    working_dir: /var/www/html
    networks:
      - crm_network
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: 'mysql'
      DB_HOST: 'crm-mysql'
      DB_PORT: '3306'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    ports:
      - '8100:80'
    
  mysql:
    image: 'mysql:8.0.42'
    container_name: crm-mysql
    restart: unless-stopped
    ports:
    - '3307:3306'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - crm_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 3
      timeout: 5s

networks:
  crm_network:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
