version: '3.8'

services:
  crm_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-app
    restart: unless-stopped
    working_dir: /app
    networks:
      - crm_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # Explicitly define the environment variables to ensure correctness
      - DB_CONNECTION=mysql
      - DB_HOST=crm-mysql
      - DB_PORT=3306
      - DB_DATABASE=crm_db
      - DB_USERNAME=pixelip
      - DB_PASSWORD=Kang@2k25
      - DB_ROOT_PASSWORD=Kang@2k25
    ports:
      - '8100:8000'

  mysql:
    image: 'mysql:8.0.42'
    container_name: crm-mysql
    restart: unless-stopped
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'crm_db'
      MYSQL_USER: 'pixelip'
      MYSQL_PASSWORD: 'Kang@2k25'
      MYSQL_ROOT_PASSWORD: 'Kang@2k25'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - crm_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 3
      timeout: 5s

networks:
  crm_network:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
